

simple_server_example: simple_server_example.cpp
	${CXX} simple_server_example.cpp -o simple_server_example -I../include -std=c++17 -lstdc++fs -g

simple_html_example: simple_html_example.cpp
	${CXX} simple_html_example.cpp -o simple_html_example -I../include -std=c++17 -g

all: simple_server_example simple_html_example
